name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.9

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
        shell: bash

      - name: Install PyInstaller
        run: |
          pip install pyinstaller
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller src/udping.py --onefile --distpath dist/
          pyinstaller src/udping_server.py --onefile --distpath dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: udping-${{ matrix.os }}-${{ github.sha }}
          path: dist/